from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class Bet(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    created_at = db.Column(db.DateTime)
    sportsbook = db.Column(db.String(100))
    sport = db.Column(db.String(50))
    league = db.Column(db.String(100))
    event_name = db.Column(db.String(255))
    game_id = db.Column(db.String(100))
    event_start_date = db.Column(db.DateTime)
    market_name = db.Column(db.String(255))
    bet_name = db.Column(db.String(255))
    odds = db.Column(db.Integer)
    clv = db.Column(db.Integer)
    clv_source = db.Column(db.String(100))
    stake = db.Column(db.Numeric(10,2))
    potential_payout = db.Column(db.Numeric(10,2))
    status = db.Column(db.String(50))
    bet_type = db.Column(db.String(50))
    bet_profit = db.Column(db.Numeric(10,2))
    notes = db.Column(db.Text)
    is_live_bet = db.Column(db.Boolean)
    is_free_bet = db.Column(db.Boolean)
    is_odds_boost = db.Column(db.Boolean)
    percentage = db.Column(db.Numeric(5,2))
    market_width = db.Column(db.Integer)
    saved_filter_name = db.Column(db.String(255))
    parlay_id = db.Column(db.String(100))
    tags = db.Column(db.Text)
    confirmed_settlement = db.Column(db.Boolean, default=None)
    created_at_db = db.Column(db.DateTime, default=db.func.current_timestamp())